"""adeed matrix update time

Revision ID: 3c19038b1b28
Revises: bc8530ea4afa
Create Date: 2023-03-01 21:25:15.203235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c19038b1b28'
down_revision = 'bc8530ea4afa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matrix', sa.Column('update_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matrix', 'update_datetime')
    # ### end Alembic commands ###
