"""some message2

Revision ID: 549cc292e747
Revises: 5cb8ef0388f0
Create Date: 2023-03-01 20:40:47.207650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549cc292e747'
down_revision = '5cb8ef0388f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_consts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('charges_count', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('last_shot', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_shot')
    op.drop_column('user', 'charges_count')
    op.drop_table('my_consts')
    # ### end Alembic commands ###
