"""adeed skins

Revision ID: bc8530ea4afa
Revises: 549cc292e747
Create Date: 2023-03-01 21:14:26.464763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc8530ea4afa'
down_revision = '549cc292e747'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('skin', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'skin')
    # ### end Alembic commands ###
